Updates on Bump Version
modl-ai/ci-workflows pull request #7
Opened 2023-03-07 14:12 UTC by sotunboolamide

**Description :**
There is need to add a flag for if changes were detected. The used action : [stefanzweifel](https://github.com/stefanzweifel)
/
[git-auto-commit-action](https://github.com/stefanzweifel/git-auto-commit-action) for passing commits have the outputs for the changes detected . 

**Updates:**

- [ ] Add the changes_detected flag
- [ ] Use the action output for commit hash instead of another step : https://github.com/stefanzweifel/git-auto-commit-action/blob/master/action.yml

2023-03-07 14:35 UTC, sotunboolamide commented
This PR would be useful in the completing hte git unification PR on u[nity plugin](https://github.com/modl-ai/UnityPlugin/pull/352)

2023-03-08 07:32 UTC, bermell approved these changes
I think this looks nice! 👍  With the caveat that I haven't tested anything. Two concerns, feel free to ignore if you don't agree: 

* The documentation is duplicated between the actual script files and the .md-file which risks diverging over time. An alternative could be to simply stated that documentation of the arguments and outputs are in the script files and only provide usage examples in the readme. 

* The documentation of the `branch` argument says "[...] required if Action is used on 'pull_request' event". Just a thought that struck me: is there a risk this is breaking existing workflows?

2023-03-10 14:08 UTC, sysnet-ai requested changes
Why do we need the 'something changed' flag?

2023-03-10 14:08 UTC, sysnet-ai commented on .github/workflows/bump_version.yml
> +      branch:
Why is this necessary?
Is there a specific need somewhere that created this requirement? - We use this action in a lot of places and have never needed this output.

2023-03-10 14:08 UTC, sysnet-ai commented
@bermell 
> The documentation is duplicated between the actual script files and the .md-file which risks diverging over time

No, this isn't quite correct - the documentation is *CREATED FROM* the script's documentation, specifically to prevent divergence.

See: https://github.com/modl-ai/ci-workflows/blob/main/scripts/auto_doc.py (Or check the commits that updated the MD, they're marvin's)

2023-03-10 14:51 UTC, sotunboolamide commented on .github/workflows/bump_version.yml
> +      branch:
The flag was required to complete the unification on unity plugin : https://github.com/modl-ai/UnityPlugin/pull/352 .

This is the exact place it was required : https://github.com/modl-ai/UnityPlugin/blob/main/.github/workflows/on_push_unity_plugin_pipeline.yml#:~:text=changed%3A%20%24%7B%7B%20steps.commit.outputs.changes_detected%20%7D%7D

It was used here : https://github.com/modl-ai/UnityPlugin/blob/main/.github/workflows/on_push_unity_plugin_pipeline.yml#:~:text=run%3A%20echo%20%24%7B%7B%20needs.package%2Dversion.outputs.changed%20%7D%7D

2023-03-10 14:54 UTC, sysnet-ai commented on .github/workflows/bump_version.yml
> +      branch:
So - it seems that it existed in that flow, but what for?
If you don't have changes, you can't generate a commit.

I don't understand what type of case we're preventing or what special path we need this for - Basically, if we don't have this flag, what would happen that we don't want?

2023-03-10 16:52 UTC, sysnet-ai commented on .github/workflows/bump_version.yml
> +      branch:
> In all , this attempt is to preserve the intent of the authors of the repo to guarantee the original behaviour of the ci

I definitely commend this as good secondary goal - but we're changing an underlying system (the ci-workflow job) to support this intent. So, we need to not only respect the intent - but understand it.

> I believe could cause of potential for a package with no changes submitted in the unity plugin

This is what I'm hinting at, there seems to be a *belief* that this is needed - But under what circumstance would this CI workflow work if there were no changes?
This flow is triggered by 2 things:
- Commits: Which can't be done without a change. Git will literally not allow it, as it makes no sense.
- Push to main: Which again, would require an empty PR to merge into main - Which I don't think is possible.

So with all this said, I cannot come up with a scenario in which we would think that line of code, and have no changes - I just can't see how it could happen, and therefore I don't see why should we support it. More code is more maintenance burden for us.

2023-03-10 17:03 UTC, sotunboolamide commented on .github/workflows/bump_version.yml
> +      branch:
Yes , you correctly analysed the situation of this case not a necessary step and would not cause any alteration in the final goal . 

But in actual fact the changes is less code .The original code was a repetition of the some of the outputs already given in the used [ci-work ](https://github.com/marketplace/actions/git-auto-commit)
Here : 
```
- name: Get SHA of Latest Commit
        id: sha
        run: |
          sha_new=$(git rev-parse HEAD)
          echo $sha_new
          echo "SHA=$sha_new" >> $GITHUB_OUTPUT
```
The ci work flow used have an output commit_hash that returns this value plus the flag needed in Unity plugin .

2023-03-10 17:58 UTC, sysnet-ai commented on .github/workflows/bump_version.yml
> +      branch:
Yeah I think pulling the Hash from the commit action is correct.

What I think we shouldn't do is add the 'things changed' flag - doesn't really seem to make a lot of sense for this action (it will *always* have changes, we just changed the file via bump2version)

And on closer inspection - The Unity action does *nothing* with that value, it just prints it.

```
    steps:
      - name: Check if stuff changed
        run: echo ${{ needs.package-version.outputs.changed }}
```

This is either debugging code, or a vestige of a previous way of doing things - which means we probably want to remove it rather than enshrine it in a 'centralized' workflow.

2023-03-10 18:43 UTC, bermell commented
> @bermell 
> > The documentation is duplicated between the actual script files and the .md-file which risks diverging over time
> 
> No, this isn't quite correct - the documentation is *CREATED FROM* the script's documentation, specifically to prevent divergence.
> 
> See: https://github.com/modl-ai/ci-workflows/blob/main/scripts/auto_doc.py (Or check the commits that updated the MD, they're marvin's)
> 
> 

Yes, David also explained the other day. I learned a thing! :) thanks both!

2023-03-13 10:29 UTC, sotunboolamide commented
I removed the changed detected flag as discussed in the PR . I think it is fine to go main now with the other changes .

2023-03-13 12:53 UTC, bermell approved these changes
Re-approving!

2023-03-14 14:49 UTC, sotunboolamide commented
I removed the changed detected flag as discussed in the PR . I think it is fine to go main now with the other changes .

2023-04-03 12:10 UTC, sysnet-ai approved these changes

2023-04-03 12:24 UTC, merged